Feature: add User, Film, UserController, FilmController. Add tests for UserController and FilmController
PavelKonkin/java-filmorate pull request #5
Opened 2023-12-21 17:21 UTC by PavelKonkin

2023-12-22 18:00 UTC, vlolad requested changes
Привет!

Все очень хорошо, есть пару моментов по валидации, которые можно улучшить. Попробуй большую часть положить на плечи аннотаций, сейчас ими вполне можно закрыть валидацию большей части данных. Это больше пожелание, чтобы добить доп. задание)

Для ловли ошибок, которые возникают при валидации, поможет класс с @controlleradvice (если захочется углубиться), но будет на следующем спринте)

В остальном - всё хорошо, тесты покрывают весь код и пограничные значения)

Хороших выходных!

2023-12-24 10:31 UTC, PavelKonkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean validate(Film film) {
Тогда из тестов убрать придется всё, что тестирует ошибки? Или нужно будет использовать что-то для мок запросов

2023-12-25 15:33 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private boolean validate(Film film) {
Там будет просто другая ошибка выбрасываться, в тестах надо будет её учесть

2023-12-25 15:39 UTC, vlolad approved these changes
Все супер с:

2023-12-25 15:39 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/validator/NoSpaces.java
> +public @interface NoSpaces {
Вот с кастомными валидаторами огонь!

2023-12-25 15:39 UTC, vlolad commented on src/main/java/ru/yandex/practicum/filmorate/controller/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Супер, что реализовал, лучше его как можно раньше вплетать в спринговый проект - все ошибки будут удобно в одном месте сразу обрабатываться)

Единственное - можно в пакет exception перенести, т.к. это не совсем про контроллеры (потом будут ещё ошибки на сервисном слое, но это уже на будущие спринты)

2023-12-25 17:54 UTC, merged